#!/bin/bash
pull:
	git pull
push:
	git add .
	git commit
	git push --repo=git@github.com:XDerekMaierX/$(pwd | sed 's/.*\///g').git -q
	git pull
viewChanges:
	git log -p
forcePullMaster:
	git fetch --all
	git reset --hard origin/master
